- name: Server info
  hosts: all
  remote_user: azureuser
  become: yes
  tasks:
   - name: Create server-info.txt
     template:
       src: info.j2
       dest: /tmp/server-info.txt

   - name: Display status
     debug:
       msg: "{{ ansible_facts['selinux']['status'] }}"

   - name: Create httpd.out
     template:
       src: se.j2
       dest: /tmp/se.out
