- name: Server info
  hosts: all
  vars:
    test_var: testing
  remote_user: azureuser
  become: yes
  tasks:
   - name: Create server-info.txt
     template:
       src: info.j2
       dest: /tmp/server-info.txt

   - name: Display status
     debug:
       msg: "{{ ansible_facts['selinux']['status'] }}"

   - name: Create se.out
     template:
       src: se.j2
       dest: /tmp/se.out

   - name: creates users files
     file:
       path: /tmp/ansible-{{ item }}
       state: touch
     loop:
       - test.conf
       - test1.conf
       - test2.conf
   
   - name: Create conf
     template: src=test.conf.j2 dest=/tmp/test.conf

